# =============================================================================
# modules/executive.py — Section 12: Executive Summary
# =============================================================================

import pandas as pd
from datetime import datetime


def generate_executive_summary(
    df:       pd.DataFrame,
    risk_df:  pd.DataFrame,
    trend_df: pd.DataFrame,
    year:     int = None,
) -> str:
    """Auto-generate executive summary as a formatted string."""
    if year is None:
        year = int(df['year'].mode()[0]) if 'year' in df.columns else 'N/A'

    lines = []
    lines.append('=' * 70)
    lines.append('  EXECUTIVE SUMMARY — PRODUCT QUALITY REVIEW (PQR)')
    lines.append(f'  Period: Year {year}')
    lines.append(f'  Generated by: PQR Anomaly Detection System v1.0')
    lines.append('=' * 70)

    for prod in df['product-name'].unique():
        sub_df    = df[df['product-name'] == prod]
        sub_risk  = risk_df[risk_df['product-name'] == prod] if not risk_df.empty else pd.DataFrame()
        sub_trend = trend_df[trend_df['product-name'] == prod] if not trend_df.empty else pd.DataFrame()

        n_total       = len(sub_df)
        n_anomaly     = sub_risk['batch-number'].nunique() if not sub_risk.empty else 0
        n_oos         = sub_risk['is_OOS'].sum() if not sub_risk.empty else 0
        n_near        = sub_risk['risk_label'].str.contains('Near Limit').sum() if not sub_risk.empty else 0
        n_trend_alert = sub_trend['risk_assessment'].str.contains('ATTENTION').sum() if not sub_trend.empty else 0

        lines.append(f'\n{"—"*70}')
        lines.append(f'  PRODUCT: {prod}')
        lines.append(f'{"—"*70}')
        lines.append(f'  Total batches analyzed    : {n_total}')
        lines.append(f'  Anomalous batches flagged : {n_anomaly} ({round(n_anomaly/n_total*100,1)}%)')
        lines.append(f'  OOS parameters            : {n_oos}')
        lines.append(f'  Near limit (<=5%)         : {n_near}')
        lines.append(f'  Problematic trends        : {n_trend_alert}')

        if not sub_risk.empty:
            lines.append('\n  Anomalous Batch Details:')
            for batch in sub_risk['batch-number'].unique():
                b_data     = sub_risk[sub_risk['batch-number'] == batch]
                b_month    = df[df['batch-number'] == batch]['month'].values
                month_str  = f'Mo {b_month[0]}' if len(b_month) > 0 else ''
                oos_params = b_data[b_data['is_OOS'] == True]['parameter'].tolist()
                oot_params = b_data[b_data['risk_label'].str.contains('Near|Monitor')]['parameter'].tolist()

                parts = []
                if oos_params: parts.append(f"OOS: {', '.join(oos_params)}")
                if oot_params: parts.append(f"OOT: {', '.join(oot_params)}")
                detail = '; '.join(parts) if parts else 'historical anomaly, within spec'
                lines.append(f'    * {batch} ({month_str}): {detail}')

        if not sub_trend.empty:
            alerts = sub_trend[sub_trend['risk_assessment'].str.contains('ATTENTION')]
            if not alerts.empty:
                lines.append('\n  Trends Requiring Investigation:')
                for _, r in alerts.iterrows():
                    direction = 'increasing' if r['trend'] == 'increasing' else 'decreasing'
                    lines.append(
                        f"    * {r['parameter']}: {direction} trend "
                        f"(tau={r['tau']:.3f}, p={r['p_value']:.4f}, "
                        f"slope {r['slope_per_batch']:+.4f}/batch)"
                    )

        lines.append('\n  Recommendations:')
        if n_oos > 0:
            lines.append('    [!] Open CAPA for batches with OOS parameters.')
        if n_near > 0:
            lines.append('    [!] Investigate parameters approaching specification limits.')
        if n_trend_alert > 0:
            lines.append('    [!] Review manufacturing process for parameters with problematic trends.')
        if n_anomaly == 0 and n_trend_alert == 0:
            lines.append('    [OK] No significant anomalies. Process is in a controlled state.')
        elif n_oos == 0 and n_near == 0 and n_trend_alert == 0:
            lines.append('    [OK] Detected anomalies are historical and well within spec limits.')

    lines.append(f'\n{"="*70}')
    lines.append(f'  Total products : {df["product-name"].nunique()}')
    lines.append(f'  Total batches  : {len(df)}')
    lines.append(f'  Generated      : {datetime.now().strftime("%Y-%m-%d %H:%M")}')
    lines.append('=' * 70)

    return '\n'.join(lines)
